[env]
_.path = ["./node_modules/.bin"]

[tools]
node = "26.8.2"

[hooks.postinstall]
script = "npm install"

[settings]
experimental = true

[tasks.lint]
run = "npm run lint"

[tasks.ci]
depends = ["lint"]
